In [2]:
print("Let's get started with encoding")

Let's get started with encoding


In [3]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [4]:
document =  ["My name is Taksh and I love AI and a dietitian"]

In [5]:
documents = ["people watch movie", 
             "people watch cricket",
             "people like movie",
             "So I hate movies",
             "I am Taksh and I like a dietitian and AI field as a whole"]

In [6]:
tokens= [sentence.lower().split() for sentence in documents]

In [7]:
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['so', 'i', 'hate', 'movies'],
 ['i',
  'am',
  'taksh',
  'and',
  'i',
  'like',
  'a',
  'dietitian',
  'and',
  'ai',
  'field',
  'as',
  'a',
  'whole']]

In [8]:
all_words = [[word] for sentence in tokens for word in sentence]

This is the input format `Word2Vec` expects — a list of "sentences", where each "sentence" is a list of tokens. By wrapping individual words, each word becomes its own one-word sentence, which is a common approach when training on individual vocabulary items rather than full sentences.

In [9]:
all_words

[['people'],
 ['watch'],
 ['movie'],
 ['people'],
 ['watch'],
 ['cricket'],
 ['people'],
 ['like'],
 ['movie'],
 ['so'],
 ['i'],
 ['hate'],
 ['movies'],
 ['i'],
 ['am'],
 ['taksh'],
 ['and'],
 ['i'],
 ['like'],
 ['a'],
 ['dietitian'],
 ['and'],
 ['ai'],
 ['field'],
 ['as'],
 ['a'],
 ['whole']]

`sparse_output=False` means the encoder returns a NumPy array instead of a sparse matrix. This makes the output easier

In [10]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown= 'ignore')

In [11]:
encoder.fit(all_words) 

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [12]:
print("vocabulary: ", encoder.categories_)

vocabulary:  [array(['a', 'ai', 'am', 'and', 'as', 'cricket', 'dietitian', 'field',
       'hate', 'i', 'like', 'movie', 'movies', 'people', 'so', 'taksh',
       'watch', 'whole'], dtype=object)]


In [13]:
token= [word.lower().split() for word in document]
token

[['my',
  'name',
  'is',
  'taksh',
  'and',
  'i',
  'love',
  'ai',
  'and',
  'a',
  'dietitian']]

In [14]:
for sentence in token:
    print(sentence)

['my', 'name', 'is', 'taksh', 'and', 'i', 'love', 'ai', 'and', 'a', 'dietitian']


In [15]:
for sentence in token:
    encoded_sentence = encoder.transform([[word] for word in sentence])  
    print(f"\nSentence: {sentence}")
    print(encoded_sentence)


Sentence: ['my', 'name', 'is', 'taksh', 'and', 'i', 'love', 'ai', 'and', 'a', 'dietitian']
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### BOW

`Bag of Words (BOW)` represents a document as a vector of word counts, ignoring order and grammar. And `Sklearn.CountVectorizer` does this in one step.

- **Ignores word order**: "dog bites man" = "man bites dog"                                         
- **No semantic meaning**: "movie" and "film" are treated as completely unrelated                      
- **Sparse vectors**: 10k vocab → mostly zeros per document                                             
- **Common words dominate**: "the", "is", "a" get "high counts despite carrying no meaning      

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:

documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [18]:
document = ["Taksh is a good learner but he struggles as soon as he distracts himself scrolling through social media"]

In [19]:
bow = CountVectorizer()

In [20]:
bow_matrix = bow.fit_transform(document)

In [21]:
bow_matrix

<1x15 sparse matrix of type '<class 'numpy.int64'>'
	with 15 stored elements in Compressed Sparse Row format>

In [22]:
print("BOW Matrix:\n", bow_matrix.toarray())

BOW Matrix:
 [[2 1 1 1 2 1 1 1 1 1 1 1 1 1 1]]


In [23]:
print("\nVocabulary", bow.get_feature_names_out())


Vocabulary ['as' 'but' 'distracts' 'good' 'he' 'himself' 'is' 'learner' 'media'
 'scrolling' 'social' 'soon' 'struggles' 'taksh' 'through']


In [24]:
bow.fit(documents)

CountVectorizer()

In [25]:
bow.transform(documents).toarray()

array([[1, 1, 0, 0, 0, 2, 1, 2],
       [0, 1, 2, 0, 0, 0, 1, 2],
       [0, 1, 0, 2, 1, 2, 1, 0],
       [0, 0, 1, 1, 0, 0, 1, 0]])

### TF-IDF Practical

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
documents = ["people love to go out in the summer", 
             "people like to watch cricket matches in summer",
             "people like to drink cold beverage in summer",
             "people like to take vacation in summer"]

In [28]:
tf_idf = TfidfVectorizer()

In [29]:
tf_idf_vector = tf_idf.fit_transform(documents)

In [30]:
tf_idf_vector.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.44327381,
        0.23131867, 0.        , 0.44327381, 0.        , 0.44327381,
        0.23131867, 0.23131867, 0.        , 0.44327381, 0.23131867,
        0.        , 0.        ],
       [0.        , 0.        , 0.47157828, 0.        , 0.        ,
        0.24608911, 0.30100231, 0.        , 0.47157828, 0.        ,
        0.24608911, 0.24608911, 0.        , 0.        , 0.24608911,
        0.        , 0.47157828],
       [0.47157828, 0.47157828, 0.        , 0.47157828, 0.        ,
        0.24608911, 0.30100231, 0.        , 0.        , 0.        ,
        0.24608911, 0.24608911, 0.        , 0.        , 0.24608911,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.27906822, 0.34134049, 0.        , 0.        , 0.        ,
        0.27906822, 0.27906822, 0.53477584, 0.        , 0.27906822,
        0.53477584, 0.        ]])

In [31]:
tf_idf.get_feature_names_out()

array(['beverage', 'cold', 'cricket', 'drink', 'go', 'in', 'like', 'love',
       'matches', 'out', 'people', 'summer', 'take', 'the', 'to',
       'vacation', 'watch'], dtype=object)

In [32]:
print("vocabulary:", tf_idf.get_feature_names_out())

vocabulary: ['beverage' 'cold' 'cricket' 'drink' 'go' 'in' 'like' 'love' 'matches'
 'out' 'people' 'summer' 'take' 'the' 'to' 'vacation' 'watch']
