### Feature Extraction

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({'text': ["Taksh is learning AI", "Taksh is liking AI", "AI is changing", "AI is booming"], 'output': [1,1,0,0]})

In [4]:
df

,text,output
0,Taksh is learning AI,1
1,Taksh is liking AI,1
2,AI is changing,0
3,AI is booming,0


In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(ngram_range=(1,2)) # Unigrams and Bigrams

In [6]:
bow = cv.fit_transform(df['text']) # bag of words

In [7]:
print(f"Vocabulary from the given text is {cv.vocabulary_}")

Vocabulary from the given text is {'taksh': 13, 'is': 4, 'learning': 9, 'ai': 0, 'taksh is': 14, 'is learning': 7, 'learning ai': 10, 'liking': 11, 'is liking': 8, 'liking ai': 12, 'changing': 3, 'ai is': 1, 'is changing': 6, 'booming': 2, 'is booming': 5}


In [8]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 0 1 0 0 1 0 1 1 0 0 1 1]]
[[1 0 0 0 1 0 0 0 1 0 0 1 1 1 1]]


In [9]:
print(bow[2].toarray())

[[1 1 0 1 1 0 1 0 0 0 0 0 0 0 0]]


In [10]:
cv.transform(['Taksh is learning and liking AI']).toarray()

array([[1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1]])

#### TF-IDF

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf= TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.35455723, 0.        , 0.        , 0.35455723, 0.67943473,
        0.        , 0.53567415],
       [0.35455723, 0.        , 0.        , 0.35455723, 0.        ,
        0.67943473, 0.53567415],
       [0.41988018, 0.        , 0.8046125 , 0.41988018, 0.        ,
        0.        , 0.        ],
       [0.41988018, 0.8046125 , 0.        , 0.41988018, 0.        ,
        0.        , 0.        ]])

In [15]:
tfidf.idf_ # IDF values for each word in the vocabulary

array([1.        , 1.91629073, 1.91629073, 1.        , 1.91629073,
       1.91629073, 1.51082562])

In [13]:
print(tfidf.get_feature_names_out())

['ai' 'booming' 'changing' 'is' 'learning' 'liking' 'taksh']


In [19]:
# We use log while calculating IDF to prevent the values from becoming too large. The log function helps to scale down the IDF values, making them more manageable and preventing them from dominating the TF-IDF scores.
# Suppose we have 10000 movie reviews, and the word "excellent" appears in 100 of those reviews. The IDF for "excellent" would be calculated as log(10000/100) = log(100) = 2. This means that "excellent" is relatively common across the reviews, and its IDF value reflects that. If we didn't use log, the IDF would be 10000/100 = 100, which is a much larger value and could overshadow other important words in the TF-IDF calculation.
# now we have some words like 'encyclopedia' which appear only in one document, so the IDF for that word would be log(10000/1) = log(10000) = 4. This indicates that 'encyclopedia' is a very rare word across the reviews, and its high IDF value reflects its uniqueness.
# if the value is bigger of IDF then after multiplying with TF, the TF-IDF score will be higher, indicating that the word is more important in that document compared to other words. Conversely, if the IDF value is smaller, the TF-IDF score will be lower, suggesting that the word is less important in that document.
# TF shows importance of a word in a document, while IDF shows importance of a word across the entire corpus. TF-IDF combines both to give a more accurate representation of a word's importance in a specific document relative to the entire corpus.
# TF-IDF is used for text classification, information retrieval (Web search), and natural language processing tasks to identify important words in documents and improve the performance of machine learning models.

In [ ]:
# Disadvantages of TF-IDF:
# 1. It is sensitive to the size of the corpus. If you have a large corpus with many documents, the IDF values will be much greater, which can lead to overfitting.
# 2. It is sensitive to the length of the documents. If the documents are very short, the IDF values will be much smaller, which can lead to underfitting.
# 3. It is sensitive to the frequency of words. If a word appears in many documents, its IDF value will be much smaller, which can lead to underfitting.
# 4. It is sensitive to the order of words in the documents. The order of words in the documents can affect the IDF values.
# 5. It is sensitive to the vocabulary size. If the vocabulary is large, the IDF values will be much smaller, which can lead to underfitting.

#### Word2Vec

In [ ]:
# word2vec, GloVe, FastText are some of the popular word embedding techniques that can be used to convert text into numerical vectors. These techniques capture the semantic meaning of words and can be used for various natural language processing tasks such as text classification, sentiment analysis, and machine translation.
# Word2Vec is a popular word embedding technique that uses a shallow neural network to learn word representations. It can be trained using either the Continuous Bag of Words (CBOW) or the Skip-Gram model. CBOW predicts the target word based on the context words, while Skip-Gram predicts the context words based on the target word.
# word2vec uses low dimensional dense vectors to represent words, which can capture semantic relationships between words. For example, the vector for "king" minus the vector for "man" plus the "woman" vector can be used to capture the semantic relationship between "king" and "queen".


In [20]:
from gensim.models import Word2Vec, KeyedVectors

In [29]:
%pip install wget

/Users/takshpatel/Desktop/GenAI-Course-Implementation/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.


In [30]:
%wget -c https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz

UsageError: Line magic function `%wget` not found.
