### Feature Extraction

In [1]:
import numpy as np
import pandas as pd

In [11]:
df = pd.DataFrame({'text': ["Taksh is learning AI", "Taksh is liking AI", "AI is changing", "AI is booming"], 'output': [1,1,0,0]})

In [12]:
df

,text,output
0,Taksh is learning AI,1
1,Taksh is liking AI,1
2,AI is changing,0
3,AI is booming,0


In [13]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()

In [ ]:
bow = cv.fit_transform(df['text']) # bag of words

In [15]:
print(f"Vocabulary from the given text is {cv.vocabulary_}")

Vocabulary from the given text is {'taksh': 6, 'is': 3, 'learning': 4, 'ai': 0, 'liking': 5, 'changing': 2, 'booming': 1}


In [16]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 1 1 0 1]]
[[1 0 0 1 0 1 1]]


In [17]:
print(bow[2].toarray())

[[1 0 1 1 0 0 0]]


In [18]:
cv.transform(['Taksh is learning and liking AI']).toarray()

array([[1, 0, 0, 1, 1, 1, 1]])