### Feature Extraction

In [28]:
import numpy as np
import pandas as pd

In [29]:
df = pd.DataFrame({'text': ["Taksh is learning AI", "Taksh is liking AI", "AI is changing", "AI is booming"], 'output': [1,1,0,0]})

In [30]:
df

,text,output
0,Taksh is learning AI,1
1,Taksh is liking AI,1
2,AI is changing,0
3,AI is booming,0


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(ngram_range=(1,2)) # Unigrams and Bigrams

In [32]:
bow = cv.fit_transform(df['text']) # bag of words

In [33]:
print(f"Vocabulary from the given text is {cv.vocabulary_}")

Vocabulary from the given text is {'taksh': 13, 'is': 4, 'learning': 9, 'ai': 0, 'taksh is': 14, 'is learning': 7, 'learning ai': 10, 'liking': 11, 'is liking': 8, 'liking ai': 12, 'changing': 3, 'ai is': 1, 'is changing': 6, 'booming': 2, 'is booming': 5}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 0 1 0 0 1 0 1 1 0 0 1 1]]
[[1 0 0 0 1 0 0 0 1 0 0 1 1 1 1]]


In [35]:
print(bow[2].toarray())

[[1 1 0 1 1 0 1 0 0 0 0 0 0 0 0]]


In [36]:
cv.transform(['Taksh is learning and liking AI']).toarray()

array([[1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1]])